import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Comp/Header";
import Navbar from "./Comp/Navbar";
import Banner from "./Comp/Banner";
import Footer from "./Comp/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
           <Header/>
           <Navbar/>
        {children}
        <Footer/>
       
      </body>
    </html>
  );
}
